### PR TITLE
fix(direnv): accept null loadedRC state

### LINKED ISSUE #7132: direnv module shows `unknown direnv state` in Ghostty v1.2.3
#### Current Behavior
The `direnv` module displays the warning `[WARN] - (starship::modules::direnv): unknown direnv state`, after navigating into a directory with a blocked `.envrc`, when using the Ghostty terminal.

1. Enable the `direnv` module in starship
2. Create a directory with an `.envrc` file
3. Navigate into the directory: `cd ./example`

```
[WARN] - (starship::modules::direnv): unknown direnv state
direnv: error /home/lucas/dev/time-canvas/.envrc is blocked. Run `direnv allow` to approve its content
```

When pressing enter a second time, the warning doesn't show up and the prompt gets displayed correctly. The error happens only when direnv first tries to run. I tested the same behavior using Kitty and the VSCode terminal, and the problem didn't occur there.

#### Expected Behavior
The prompt should display correctly after navigating into a directory including a blocked `.envrc file`. The warning shouldn't show up.

#### Additional context/Screenshots
Image

#### Environment
- Starship version: 1.24.1
- bash version: GNU bash, version 5.3.3(1)-release (x86_64-pc-linux-gnu)
- Operating system: NixOS 25.11.0
- Terminal emulator: Ghostty 1.2.3
- Git Commit Hash: 
- Branch/Tag: 
- Rust Version: rustc 1.90.0 (1159e78c4 2025-09-14) (built from a source tarball)
- Rust channel:  release
- Build Time: 1980-01-01 00:00:00 +00:00
#### Relevant Shell Configuration

```bash
# Commands that should be applied only for interactive shells.
[[ $- == *i* ]] || return

HISTFILESIZE=100000
HISTSIZE=10000

shopt -s histappend
shopt -s checkwinsize
shopt -s extglob
shopt -s globstar
shopt -s checkjobs



if [[ ! -v BASH_COMPLETION_VERSINFO ]]; then
  . "/nix/store/an1k68bpqj8sas0zcd3dq33pjkphkb8a-bash-completion-2.17.0/etc/profile.d/bash_completion.sh"
fi

if [[ -n "${GHOSTTY_RESOURCES_DIR}" ]]; then
  builtin source "${GHOSTTY_RESOURCES_DIR}/shell-integration/bash/ghostty.bash"
fi

if [[ $TERM != "dumb" ]]; then
  eval "$(/nix/store/i8836mw8kyv2q3m1dfa5bzvliap2hmk3-starship-1.24.1/bin/starship init bash --print-full-init)"
fi

if test -n "$KITTY_INSTALLATION_DIR"; then
  export KITTY_SHELL_INTEGRATION="no-rc"
  source "$KITTY_INSTALLATION_DIR/shell-integration/bash/kitty.bash"
fi

eval "$(/nix/store/bc9arrsjlaljzy5zmm1hbsh5z26h38b0-direnv-2.37.1/bin/direnv hook bash)"
```

#### Starship Configuration

```toml
add_newline = false
format = "$username$directory$git_branch$git_commit$git_status$nix_shell$direnv\n$character"
palette = "base16"

[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](white)"

[directory]
disabled = false
format = "[](bright-black inverted)[ $path ](bg:bright-black $style)[](bright-black)"
read_only_style = "bright-red"
repo_root_format = "[](bright-black inverted)[ $before_root_path](bg:bright-black $before_repo_root_style)[$repo_root](bg:bright-black $repo_root_style)[$path ](bg:bright-black $style)[](bright-black)"
repo_root_style = "bold bright-yellow"
style = "bright-white"
truncate_to_repo = true
truncation_length = 6
truncation_symbol = "…/"

[direnv]
allowed_msg = ""
denied_msg = ""
disabled = false
format = "[](blue inverted)[ $symbol$loaded$allowed ](bg:blue $style)[](blue)"
loaded_msg = ""
not_allowed_msg = ""
style = "black"
unloaded_msg = ""

[git_branch]
disabled = false
format = "[](bright-green inverted)[ $symbol$branch ](bg:bright-green $style)"
style = "black"

[git_commit]
disabled = false
format = "[](bright-green inverted)[  $hash$tag ](bg:bright-green $style)"
only_detached = true
style = "black"

[git_status]
ahead = "↑${count}"
behind = "↓${count}"
conflicted = "🞪${count}"
deleted = "-${count}"
disabled = false
diverged = "↑${ahead_count}↓${behind_count}"
format = "([\\[$ahead_behind$all_status\\] ](bg:bright-green $style))[](bright-green)"
modified = "~${count}"
renamed = "»${count}"
staged = "+${count}"
stashed = "\\$${count}"
style = "black"
untracked = "?${count}"

[nix_shell]
disabled = false
format = "[](blue inverted)[ $symbol ](bg:blue $style)[](blue)"
style = "black"
symbol = "󱄅"

[username]
disabled = false
format = "[](bright-black)[ $user ](bg:bright-black $style)[](bright-black)"
show_always = true
style_root = "bold bright-purple"
style_user = "bold bright-green"

```

### PR DESCRIPTION
**Pull request by Acture**
#### Description
Treat `direnv status --json` payloads where `foundRC` is present but `loadedRC` is `null` as a valid unloaded state instead of falling back to the legacy parser and logging `unknown direnv state`.

This keeps the existing behavior for loaded states, hides the module when both `foundRC` and `loadedRC` are `null`, and continues to reject inconsistent payloads where `loadedRC` is present but `foundRC` is missing.

#### Motivation and Context
Closes #7132.

This fixes a prompt-state parsing issue in the `direnv` module. During prompt initialization, `direnv` can report a valid intermediate JSON state with `foundRC != null` and `loadedRC == null`. Starship currently treats that payload as invalid, falls back to the legacy parser, and logs a warning even though `direnv` still activates correctly.

#### How Has This Been Tested?
- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

Commands run on macOS:
- `cargo fmt`
- `cargo test direnv`
- `TERM=xterm-256color cargo test`
- `cargo clippy --all-targets --all-features`

Added coverage for:
- parsing `foundRC != null && loadedRC == null` as a valid unloaded state
- rejecting `foundRC == null && loadedRC != null`
- rendering unloaded `allowed`, `not allowed`, and `denied` states from JSON input

#### Checklist:
- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

File: src/modules/direnv.rs [hunk 1]
```diff
@@ -30,13 +30,24 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
     // the `--json` flag is silently ignored for direnv versions <2.33.0
     let direnv_status = &context.exec_cmd("direnv", &["status", "--json"])?.stdout;
-    let state = match DirenvState::from_str(direnv_status) {
-        Ok(s) => s,
-        Err(e) => {
-            log::warn!("{e}");
+    let state = match serde_json::from_str::<RawDirenvState>(direnv_status) {
+        Ok(raw) => match raw.into_direnv_state() {
+            Ok(Some(s)) => s,
+            Ok(None) => return None,
```
Comment (davidkna) [inline src/modules/direnv.rs]:
```suggestion
            Ok(s) => return s,
```

File: src/modules/direnv.rs [hunk 2]
```diff
@@ -30,13 +30,24 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
+        Err(_) => match DirenvState::from_lines(direnv_status) {
+            Ok(s) => s,
+            Err(e) => {
+                log::warn!("{e}");
 
-            return None;
-        }
+                return None;
+            }
+        },
```
Comment (davidkna) [inline src/modules/direnv.rs]: Please simplify this block a bit, it currently has some superfluous match arms, instead of `match` I feel like combinators are appropriate here:
```rs
let state = serde_json::from_str::<RawDirenvState>(direnv_status)
    .ok()
    .and_then(|raw| raw.into_direnv_state().inspect_err(|e| log::warn!("Failed... :{e}")).ok())
    .flatten()
    .or_else(|| {
        DirenvState::from_lines(direnv_status)
            .inspect_err(|e| log::warn!("Failed....: {e}"))
            .ok()
    })?;
```

Comment (Acture) [reply src/modules/direnv.rs]: should be fixed now

**Comment by davidkna** [comment]
Thanks for the contribution @Acture!
