### PR TITLE
fix(dart): detect version output in stdout with dart 2.15+

### LINKED ISSUE #3341: Dart version is not shown at all.
#### Current Behavior
With default dart module config I am shown `via 🎯 `, when I am in directory with dart project.

#### Expected Behavior
It should show the version. The output should be `via 🎯 2.15.1`

#### Additional context/Screenshots
I have not installed dart directly but is shipped with flutter. The output of `dart --version` is `Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "linux_x64"`. I cross checked with the parse function in code (I am not a Rust developer) - looks like the implementation is correct, not sure where it is failing

#### Environment
- Starship version: 1.0.0
- bash version: GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- Operating system: Ubuntu 20.04
- Terminal emulator: <unknown terminal> <unknown version>
- Git Commit Hash: dfbf861f
- Branch/Tag: v1.0.0
- Rust Version: rustc 1.56.1 (59eed8a2a 2021-11-01)
- Rust channel:  release
- Build Time: 2021-11-09 21:35:52 +00:00
#### Relevant Shell Configuration

```bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi


## show git branch name in PS1
# default PS1=\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$
git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
export PS1="\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\[\033[01;31m\]\$(git_branch)\[\033[00m\]\$ "


# Flutter env
export PATH="$PATH:/home/harsh/flutter/flutter/bin"
export CHROME_EXECUTABLE="/snap/bin/brave"
alias fork-flutter='/home/harsh/forks/flutter/bin/flutter'

# Android env
export ANDROID_HOME="/home/harsh/Android/Sdk"
export PATH="$PATH:/home/harsh/Android/Sdk/platform-tools"

# Home
export PATH="$PATH:/home/harsh"

# Next Home Flutter alias
. /home/harsh/AndroidStudioProjects/next_home/.alias

# Next Home Alexa Skill alias
. /home/harsh/PycharmProjects/next-home-alexa-skill/.alias 

#k8s
export KUBECONFIG=$HOME/.kube/config

# Next Home helmfile alias
alias helmfile-local='helmfile --interactive -e local'
alias helmfile-staging='helmfile --interactive -e staging'
alias helmfile-production='helmfile --interactive -e production'

# set editor
export EDITOR=nano

# pgo
export PATH=/home/h

### PR DESCRIPTION
**Pull request by laxtiz**
#### Description

flutter 2.8.0 updated with dart 2.15, command `dart --version` will output in stdout.

#### Motivation and Context

Closes #3341 

#### Screenshots (if appropriate):
2021-12-24 16-51-18 的屏幕截图

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

File: src/modules/dart.rs [hunk 1]
```diff
@@ -32,8 +33,8 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
             })
             .map(|variable| match variable {
                 "version" => {
-                    let dart_version =
-                        parse_dart_version(&context.exec_cmd("dart", &["--version"])?.stderr)?;
+                    let command = context.exec_cmd("dart", &["--version"])?;
+                    let dart_version = parse_dart_version(&get_command_string_output(command))?;
```
Comment (davidkna) [inline src/modules/dart.rs:37]: Can you add a test with stdout version output? You can use `cmd` to mock the command dynamically ([example](https://github.com/starship/starship/blob/c1f2d345aac0b0241ea1b6d99977fea20fa3f5bb/src/modules/ocaml.rs#L339-L346)).

Comment (laxtiz) [reply src/modules/dart.rs:37]: Ok i will do it as soon as possible

File: src/modules/dart.rs [hunk 2]
```diff
@@ -139,4 +140,25 @@ mod tests {
...
+    fn detect_version_output_in_stdout() -> io::Result<()> {
+        // after dart 2.15.0, version info output in stdout.
+        let dir = tempfile::tempdir()?;
+        File::create(dir.path().join("any.dart"))?.sync_all()?;
+
+        let actual = ModuleRenderer::new("dart")
+            .cmd(
+                "dart --version",
+                Some(CommandOutput {
+                    stdout: String::from("Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on \"linux_x64\""),
```
Comment (davidkna) [inline src/modules/dart.rs:154]: Thanks! But I believe this should have a trailing newline.
```suggestion
                    stdout: String::from("Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on \"linux_x64\"\n"),
```

Comment (laxtiz) [reply src/modules/dart.rs:154]: But there is no new line in utils.rs
https://github.com/starship/starship/blob/10e89121595827ce99042d036b1ee55f8a3a6a08/src/utils.rs#L128-L133

Comment (davidkna) [reply src/modules/dart.rs:154]: You're right, I must have been mistaken.

**Review by davidkna — APPROVED** [review]
