### PR TITLE
fix(jobs): Handle zero jobs with zero thresholds

### LINKED ISSUE #2610: [jobs] Cannot take negative value (zero jobs not shown)
#### Current Behavior

```toml
[jobs]
threshold = -1
```

does not show 0 (zero) in the output if there are no background jobs.

#### Expected Behavior

`0` (zero) is printed for zero background jobs

#### Environment

```
$ starship --version
starship 0.51.0
branch:
commit_hash:
build_time:2021-03-29 15:35:00
build_env:rustc 1.50.0,
```

- Shell type: bash
- Shell version: 4.4.23
- Terminal emulator: Konsole
- Operating system: NixOS Linux
-

### PR DESCRIPTION
**Pull request by Anthuang**
First PR here, let me know if anything can be improved!

#### Description
Currently, if there are 0 jobs running then the jobs module doesn't show anything. However, if a negative threshold is specified (user wants to explicitly see that there are 0 jobs running), then it should show 0.

Closes #2610

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:
- [x] I have updated the documentation accordingly.

### CODE REVIEW

File: src/modules/jobs.rs [hunk 1]
```diff
@@ -15,12 +15,24 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
+
+    if config.threshold < 0 {
+        log::warn!(
+            "threshold in [jobs] ({}) was less than zero",
+            config.threshold
+        );
+        return None;
+    }
+
+    if num_of_jobs == 0 && config.threshold > 0 {
```
Comment (vladimyr) [inline src/modules/jobs.rs:27]:
```suggestion
    if num_of_jobs < config.threshold {
```

File: src/modules/jobs.rs [hunk 2]
```diff
@@ -15,12 +15,24 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
         return None;
     }
 
     let module_number = if num_of_jobs > config.threshold {
         num_of_jobs.to_string()
+    } else if num_of_jobs == 0 && config.threshold == 0 {
+        // Explicitly show when there are 0 background jobs
+        "0".to_string()
```
Comment (vladimyr) [inline src/modules/jobs.rs:35]: You don't need separate branch. If threshold is zero number will always get printed.
```suggestion
    let module_number = if num_of_jobs > config.threshold || config.threshold == 0 {
        num_of_jobs.to_string()
    } else {
        "".to_string()
```

File: src/modules/jobs.rs (hunk 1 above)
Comment (Anthuang) [reply src/modules/jobs.rs:27]: The previous behavior was that if there are _any_ background jobs running, then the module would show a symbol, regardless of the threshold. Should we try to keep this same behavior?

Comment (vladimyr) [reply src/modules/jobs.rs:27]: Oh right, good catch! :+1: Let's keep existing behavior.

**Review by vladimyr — APPROVED** [review]
> First PR here, let me know if anything can be improved!

Sure, do more great PRs like this one! :heart: 

LGTM

**Comment by vladimyr** [comment]
Actually, I forgot, docs need to get updated too :upside_down_face:

**Comment by Anthuang** [comment]
> > First PR here, let me know if anything can be improved!
> 
> Sure, do more great PRs like this one! ❤️
> 
> LGTM

Thank you for the reviews!! And I just added the docs, lmk if it sounds good or if I should change the wording

**Comment by andytom** [comment]
Thank you @Anthuang for your contribution and thank you @vladimyr for the review.
