### PR TITLE
fix(style): ensure nested style variables are processed during formatting

### LINKED ISSUE #4327: Styles in git_metrics are not applied in nested groups
#### Current Behavior

When using `$added_style` or `$deleted_style` in nested groups in the `git_metrics` module, it appears that these styles are not applied correctly. Concretely, the below configuration produces the default, white on black style.

#### Expected Behavior

I would expect the configuration to produce green or red on light orange, as specified by the configuration.

#### Additional context/Screenshots

If I remove the outer text group, the styles get applied correctly.

#### Environment
- Starship version: 1.10.2
- zsh version: zsh 5.8.1 (x86_64-apple-darwin22.0)
- Operating system: Mac OS 13.0.0
- Terminal emulator: iTerm.app 3.4.16
- Git Commit Hash: 
- Branch/Tag: 
- Rust Version: rustc 1.63.0
- Rust channel:  release
- Build Time: 2022-08-19 02:43:05 +00:00

#### Starship Configuration

```toml
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$git_metrics
"""

[git_metrics]
added_style = "bg:#FCA17D bold fg:#00FF00"
deleted_style = "bg:#FCA17D bold fg:#FF0000"
disabled = false
format = "[([+$added ]($added_style))([-$deleted ]($deleted_style))](bg:#FCA17D)"
```

### PR DESCRIPTION
**Pull request by Ajpantuso**
#### Description

Current logic used to identify style variables in the `StringFormatter` does not descend into nested `TextGroup`s causing improper style formats when style variables are used in nested contexts. This change trivially fixes that.

#### Motivation and Context

Closes #4327

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

File: src/formatter/string_formatter.rs [hunk 1]
```diff
@@ -569,6 +569,23 @@ mod tests {
...
+        const FORMAT_STR: &str = "[[text]($style)](blue)";
+        let inner_style = Some(Color::Red.bold());
+
+        let formatter = StringFormatter::new(FORMAT_STR)
+            .unwrap()
+            .map_style(|variable| match variable {
+                "style" => Some(Ok("red bold".to_owned())),
+                _ => None,
+            });
+
```
Comment (davidkna) [inline src/formatter/string_formatter.rs:583]: The changes LGTM, but lets also test this:

```suggestion

        assert_eq!(
            formatter.style_variables.keys().collect::<Vec<_>>(),
            vec!["style"]
        );

```

Comment (Ajpantuso) [reply src/formatter/string_formatter.rs:585]: Done, but applied the same assertion using the public interface.

**Review by davidkna — APPROVED** [review]

**Comment by andytom** [comment]
Thank you for your contribution @Ajpantuso and thanks for reviewing @davidkna.
