### PR TITLE
fix(git): improve bare repository detection

### LINKED ISSUE #7414: git_status not showing anything
#### Current Behavior

git status absent from terminal

#### Expected Behavior

git status should be shown like before using different symbols for modified, branch ahead, behind and divergent

#### Additional context/Screenshots

I am inside a worktree of a bare repo

#### Environment
- Starship version: 1.25.0
- zsh version: zsh 5.9 (arm64-apple-darwin25.0)
- Operating system: Mac OS 26.3.0
- Terminal emulator: ghostty 1.3.0
- Git Commit Hash: 
- Branch/Tag: 
- Rust Version: rustc 1.94.1 (e408947bf 2026-03-25) (Homebrew)
- Rust channel:  release
- Build Time: 2026-04-18 11:10:42 +00:00
#### Relevant Shell Configuration

```bash
eval "$(starship init zsh)"
```

#### Starship Configuration

```toml
# Don't print a new line at the start of the prompt
add_newline = false

command_timeout=5000

[directory]
truncation_length = 3
format = "[$path]($style)[$lock_symbol]($lock_style) "

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✖](bold red) "

[battery]
full_symbol = "🔋 "
charging_symbol = "⚡️ "
discharging_symbol = "💀 "

[[battery.display]]
threshold = 30
style = "bold red"

[python]
# Only use the `python3` binary to get the version.
python_binary = "python3"

```

### PR DESCRIPTION
**Pull request by ajdawson**
#### Description
When using a worktree backed by a bare repository, the is_bare() method from gix repository returns true, even though the user is in a checked out worktree. This is a change in behaviour of is_bare() some time between version 0.76.0 (used in starship v1.24.2) and 0.81.0 (used in starship v1.25.0). A better way of handling this is to instead check if workdir() returns None.

#### Motivation and Context

Closes #7414

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

File: src/modules/git_metrics.rs [hunk 1]
```diff
@@ -26,7 +26,7 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
 
     let repo = context.get_repo().ok()?;
     let gix_repo = repo.open();
-    if gix_repo.is_bare() {
+    if gix_repo.workdir().is_none() {
```
Comment (davidkna) [inline src/modules/git_metrics.rs]: Please fix the clippy warning:
```
29 | /     if gix_repo.workdir().is_none() {
30 | |         return None;
31 | |     }
   | |_____^ help: replace it with: `gix_repo.workdir()?;`
   |
```

Comment (ajdawson) [reply src/modules/git_metrics.rs]: Thank you for the reminder, I have pushed the required update.

**Comment by davidkna** [comment]
Thanks for the contribution @ajdawson!
