### PR TITLE
fix(git_state): Handle gitdir indirection when rebasing

### LINKED ISSUE #1859: Panic when rebasing in a secondary git worktree
`starship bug-report` didn't work (the page didn't load properly)

## Bug Report

To reproduce, create two worktrees with conflicts and rebase the secondary one
onto the primary's branch. Observe that starship panics when this rebase
happens in the secondary tree. I suspect this is because it expects `.git` to
be a directory instead of a file containing `gitdir:
/home/j/projects/bugs/foo/.git/worktrees/bar` (or whatever).

- `mkdir foo`
- `cd foo || exit`
- `git init`
- `git commit -m init --allow-empty`
- `git worktree add ../bar`
- `echo "hi" > foo`
- `git add foo`
- `git commit -m "hi"`
- `cd ../bar || exit`
- `echo "not-hi" > foo`
- `git add foo`
- `git commit -m "conflict"`
- `git rebase master`
  - Observe that starship now panics with

    ```
    thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', src/modules/git_state.rs:148:37
    stack backtrace:
       0:     0x55ee4622a75f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8e44e3bad104136e
       1:     0x55ee4618285d - core::fmt::write::he8cb6d64ed166147
       2:     0x55ee4623cb46 - std::io::Write::write_fmt::hf25ce96005919ce6
       3:     0x55ee46233a00 - std::panicking::default_hook::{{closure}}::hf8bcda2c877e2dcc
       4:     0x55ee462334d2 - std::panicking::rust_panic_with_hook::h7b83b0fe7900eb7a
       5:     0x55ee46233168 - rust_begin_unwind
       6:     0x55ee461814e0 - core::panicking::panic_fmt::h61e03e91a1a8868a
       7:     0x55ee46181ddc - core::panicking::panic::h2f38f7f03997361e
       8:     0x55ee4608149b - starship::modules::git_state::describe_rebase::hf9543bc4a82b6f55
       9:     0x55ee460bc9ad - starship::modules::handle::h685c7a0fa8182e5e
      10:     0x55ee460dc4c2 - starship::print::handle_module::hedc31448d387cf54
      11:     0x55ee46014bc8 - rayon::iter::plumbing::bridge_producer_consumer::helper::h864a3c8bed008420
      12:     0x55ee4602a2b8 - <rayon_core::job::StackJob<L,F,R> as rayon_core::job::Job>::execute::h0426a1ded128ad44
      13:     0x55ee461abcfe - rayon_core::registry::WorkerThread::wait_until_cold::h40ed63a6fdc6f45f
      14:     0x55ee461adeea - std::sys_common::backtrace::__rust_begin_short_backtrace::ha2f528c78a5ead61
      15:     0x55ee461ad806 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h622a186082e259c9
      16:     0x55ee462399ba - std::sys::unix::thread::Thread::new::thread_start::h2dd53bf76d714ab0
      17:     0x7efcfd59fead - start_thread
      18:     0x7efcfd4b6d2f - __GI___clone
      19:                0x0 - <unknown>

    ```

Starship should call `git rev-parse --git-dir` to get the git dir instead.

#### Environment
- Starship version: `starship 0.45.2`
- Shell type: zsh
- Shell version: zsh 5.8 (x86_64-pc-linux-gnu)

#### Starship Configuration

```toml

[aws]
disabled = true

[character]
symbol = "$"

[directory]
truncate_to_repo = false
truncation_length = 0

[git_branch]
symbol = ""

[git_status]
disabled = true

[nix_shell]
disabled = false
format = "[$symbol]($style) "
symbol = "\\[nix-shell\\]"

[package]
disabled = true

```

### PR DESCRIPTION
**Pull request by g2p**
#### Description
The first commit makes rebase status more robust by removing some unwraps in the git_state module.

Those unwraps were triggered by rebasing within git repositories using .git files (not directories) that link to the actual gitdir.

The second commit adds support for gitdir indirection.

#### Motivation and Context
starfish crashed and garbled the terminal when I was rebasing within git submodules.

Fixes #1859

#### How Has This Been Tested?
Tested before/after on local git checkouts.

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

File: src/modules/git_state.rs [hunk 1]
```diff
@@ -143,10 +143,16 @@ fn describe_rebase<'a>(root: &'a PathBuf, rebase_config: &'a str) -> StateDescri
...
+    } else {
+        (None, None)
+    };
+
     StateDescription {
         label: rebase_config,
-        current: Some(format!("{}", progress.unwrap().0)),
-        total: Some(format!("{}", progress.unwrap().1)),
+        current,
+        total,
```
Comment (davidkna) [inline src/modules/git_state.rs:165]: I think this issue has already been handled with #1761

Comment (g2p) [reply src/modules/git_state.rs:165]: The other PR fixes the crash, but git_state is still getting bad data in gitlinked repositories.

Comment (davidkna) [reply src/modules/git_state.rs:165]: Sorry I only meant those specific lines.

**Comment by expipiplus1** [comment]
Why not call out to `git rev-parse --git-dir`, are there performance considerations?

**Review by andytom — APPROVED** [review]
Thank you for the contribution @g2p. This LGTM, if you can give this a rebase and fix the merge conflicts I think we should be good to merge this.

**Comment by andytom** [comment]
> Why not call out to `git rev-parse --git-dir`, are there performance considerations?

We are planning to move away from using libgit2 and calling out to git directly in a future version but that unfortunately is still a bit of a WIP see #1446 for full details.

**Comment by g2p** [comment]
Rebased, and reworked the first patch to be on top of #1761

**Comment by andytom** [comment]
Thanks for the contribution @g2p
