### PR TITLE
fix: battery percentage character on Zsh. #226

### LINKED ISSUE #226: Battery module percentage display like '100%{' on Zsh. looks like mixed '{' Unintentionally.
#### Current Behavior
when battery module enable, show battery status like this. (I'm changed show threshold for this)
```
⚡️68%{ 🦄 💬 ❯
```

looks like mixed `{` Unintentionally.

#### Expected Behavior
```
⚡️68% 🦄 💬 ❯
```

#### Additional context/Screenshots
I see this problem on zsh.
on Bash, display `100%`.

#### Environment
- Starship version: 0.12.0
- Shell type: zsh
- Shell version: zsh 5.7.1 (x86_64-apple-darwin18.2.0)
- Shell plugin manager: none
- Terminal emulator: iTem
- Operating system: OSX 10.14.5

#### Relevant Shell Configuration
```bash
setopt correct
setopt re_match_pcre
setopt prompt_subst
autoload -U compinit
compinit
setopt COMPLETE_IN_WORD

eval "$(starship init zsh)"
```

#### Starship Configuration
```
[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"
```

#### Possible Solution

### PR DESCRIPTION
**Pull request by TsubasaKawajiri**
on Zsh, battery percentage character print `%{`.
this PR fix print `%{` -> `%`.

#### Description
on Zsh, `%` is prompt sequence prefix.
http://zsh.sourceforge.net/Doc/Release/Prompt-Expansion.html

i.e,
`%n` will print username,
`%%` will print `%`, etc.

this problem on only Zsh. Bash and Fish are print `%`.
So, switch percentage character by `STARSHIP_SHELL`.

#### Motivation and Context

Closes #226 

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Screenshots (if appropriate):
those screenshots are change `BATTERY_THRESHOLD` to `100.0` for this.
on Bash:
スクリーンショット 2019-08-25 14 54 21

on Zsh:
スクリーンショット 2019-08-25 14 44 26

on Fish:
スクリーンショット 2019-08-25 14 44 30

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

File: src/modules/battery.rs [hunk 1]
```diff
@@ -9,6 +9,12 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
     const BATTERY_DISCHARGING: &str = "⇣";
     const BATTERY_THRESHOLD: f32 = 10.0;
 
+    let shell = std::env::var("STARSHIP_SHELL").unwrap_or_default();
+    let percentage_char = match shell.as_str() {
+        "zsh" => "%%",
```
Comment (chipbuster) [inline src/modules/battery.rs]:
```suggestion
        "zsh" => "%%",   // % is an escape in zsh, see PROMPT in `man zshmisc`
```

File: src/modules/battery.rs [hunk 2]
```diff
@@ -9,6 +9,12 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
     const BATTERY_DISCHARGING: &str = "⇣";
     const BATTERY_THRESHOLD: f32 = 10.0;
```
Comment (chipbuster) [inline src/modules/battery.rs]:
```suggestion
// TODO: Update when v1.0 printing refactor is implemented to only
// print escapes in a prompt context.
```

Could you leave this note in the code so that anyone doing the 1.0 refactor will be able to look back on this?

**Comment by TsubasaKawajiri** [comment]
add few comments and, fix `STARSHIP_SHELL` for fish. 💪 

this screenshot is launch Fish in Zsh.
スクリーンショット 2019-08-26 8 52 23
