### PR TITLE
fix(explain): align table correctly

### LINKED ISSUE #1480: "explain" output alignment is foiled by multibyte unicode
#### Current Behavior
Running `starship explain` results in a misaligned table when the prompt segments are multibytes

```
 Here's a breakdown of your prompt:
 Pytest             -  The current working directory
  pytest-6.0.0rc1  -  The active branch of the repo in your current directory
 🐍 v3.8.2          -  The currently installed version of Python
 ☁️  pdx            -  The current AWS region and profile
```

#### Expected Behavior
I expect an aligned table:

```
 Here's a breakdown of your prompt:
 Pytest             -  The current working directory
  pytest-6.0.0rc1  -  The active branch of the repo in your current directory
 🐍 v3.8.2           -  The currently installed version of Python
 ☁️  pdx.             -  The current AWS region and profile
```

#### Additional context/Screenshots
Just in case markdown rendering mucks with it:

image

#### Environment
- Starship version: 0.44.0
- fish version: fish, version 3.1.2
- Operating system: Mac OS 10.15.5
- Terminal emulator: iTerm.app 3.3.10beta4

#### Relevant Shell Configuration

```bash
<unknown config>
```

#### Starship Configuration

```toml
[prompt]
add_newline = false

[line_break]
disabled = true

[aws.region_aliases]
us-east-1 = "iad"
us-east-2 = "cmh"
us-west-2 = "pdx"
```

### PR DESCRIPTION
**Pull request by davidkna**
#### Description

The table in `explain` wasn't aligned correctly. I think this happens because since v0.12.0 textwrap doesn't count ANSI escape sequences anymore. This also means `max_ansi_width` is no longer needed.
I couldn't get `{:width$}` to work the way I wanted so I replaced it with `" ".repeat(width)`.
~Also by using `UnicodeWidthStr::width` the width calculation itself should be a bit better because it can work on the level of graphemes instead of characters.~ Sadly both `UnicodeWidthStr::width` and `UnicodeWidthStr::width` appear to fail at this. I replaced them with a custom textwrapper.

#### Motivation and Context

Closes #1480 

#### Screenshots (if appropriate):
Before:
```
starship on  master [!?] is 📦 v0.44.0 via 🦀 v1.44.1
❯ starship explain

 Here's a breakdown of your prompt:
 starship          -  The current working directory
  master          -  The active branch of the repo in your current directory
 !?                -  Symbol representing the state of the repo
 📦 v0.44.0  -  The package version of the current directory's project
 🦀 v1.44.1        -  The currently installed version of Rust
```

After (this does not look aligned here but it does in my terminal):
```
 Here's a breakdown of your prompt:
 starship         -  The current working directory
 on  master      -  The active branch of the repo in your current directory
 [!?]             -  Symbol representing the state of the repo
 is 📦 v0.44.0    -  The package version of the current directory's project
 via 🦀 v1.44.1   -  The currently installed version of Rust
 ❯                -  A character (usually an arrow) beside where the text is entered in your terminal

```

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [x] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

File: src/print.rs [hunk 1]
```diff
@@ -104,50 +104,38 @@ pub fn explain(args: ArgMatches) {
...
-            info.value.chars().count() + count_wide_chars(&info.value),
-        );
-        max_module_width = std::cmp::max(max_module_width, info.value_len);
-    }
+    let max_module_width = modules.iter().map(|i| i.value_len).max().unwrap_or(0);
 
     let desc_width = term_size::dimensions()
         .map(|(w, _)| w)
-        .map(|width| width - std::cmp::min(width, max_ansi_module_width));
+        .map(|width| width - std::cmp::min(width, max_module_width + 6));
```
Comment (davidkna) [inline src/print.rs:117]: I think it makes sense to fall back to `None` instead of allowing only one char per line. Something like 4 could be a good  cutoff. Any opinions on this?

Comment (davidkna) [reply src/print.rs:117]: Also should I replace the 6 with a 7 so there's padding on both the left and right side?

**Comment by davidkna** [comment]
My newest commit doesn't show up here. I'll make a new PR tomorrow if this persists.

**Comment by davidkna** [comment]
It looks like most terminals have trouble properly displaying this kind of graphme clusters anyway and they'll actually end up as the wrong 8 characters wide.
Should I revert the custom textwrapping changes from this PR?

File: src/print.rs (hunk 1 above)
Comment (andytom) [reply src/print.rs:118]: I've tested this locally and 6 LGTM, only suggestion here would be to maybe add a comment to explain this so if we want to change it in the future it's nice an easy to find what we need to change.

File: src/print.rs [hunk 2]
```diff
@@ -104,50 +105,71 @@ pub fn explain(args: ArgMatches) {
...
-        );
-        max_module_width = std::cmp::max(max_module_width, info.value_len);
-    }
+    let max_module_width = modules.iter().map(|i| i.value_len).max().unwrap_or(0);
 
     let desc_width = term_size::dimensions()
         .map(|(w, _)| w)
-        .map(|width| width - std::cmp::min(width, max_ansi_module_width));
+        // In addition to the module width itself there are also 6 padding characters in each line.
+        // This needs to be updated here and later in the function on line formatting changes.
```
Comment (andytom) [inline src/print.rs:119]: Sorry didn't realise this earlier but if the 6 is used here are later on should we use a constant for this so they don't end up getting out of sync?

Comment (davidkna) [reply src/print.rs]: I've replaced it with a constant.

**Comment by andytom** [comment]
Thanks for the contribution @davidkna and for the quick responses.
