### PR TITLE
fix(python): Add a missing ' ' to the end of the python prompt

### LINKED ISSUE #2342: formatting issue with space for python
#### Additional context/Screenshots
I have the prompt as following, its missing a space after the python stuff before the via for ruby

image

#### Possible Solution
N/A

#### Environment
- Starship version: 0.50.0
- zsh version: zsh 5.8 (x86_64-apple-darwin20.1.0)
- Operating system: Mac OS 11.2.1
- Terminal emulator: iTerm.app 3.4.4
- Git Commit Hash: 
- Branch/Tag: 
- Rust Version: rustc 1.49.0
- Rust channel:  release
- Build Time: 2021-02-03 00:09:06
#### Relevant Shell Configuration

```bash
####################################################################################################################################
# basic setup for ZSH, source all files

# basic common configuration
. ~/.zsh/zgen.zsh
. ~/.zsh/environment.zsh
. ~/.zsh/options.zsh
. ~/.zsh/aliases.zsh
. ~/.zsh/functions.zsh
. ~/.zsh/bindkeys.zsh

# OS Specific ZSH Settings
if [ -f ~/.zsh/os.d/${ZSH_OS}.zsh ]; then
  . ~/.zsh/os.d/${ZSH_OS}.zsh
fi

# Host Specific ZSH Settings
if [ -f ~/.zsh/host.d/${ZSH_HOSTNAME}.zsh ]; then
  . ~/.zsh/host.d/${ZSH_HOSTNAME}.zsh
fi

# Programming language specific binidngs
for file in $HOME/.zsh/language.d/*.zsh; do
  source $file
done

eval "$(starship init zsh)"

####################################################################################################################################
```

#### Starship Configuration

```toml
# Don't print a new line at the start of the prompt
add_newline = false

# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """


```

### PR DESCRIPTION
**Pull request by offbyone**
#### Description

After upgrading from 0.47 to 0.49 I noticed that there was a missing ' ' between
the python format section and the one that comes after that.

#### Motivation and Context
Fixes #2342

#### Screenshots (if appropriate):

```
# this is with 0.49 release
~/p/ideas on  master [$?] via ⬢ v15.3.0 via 🐍 v3.9.1 (python-3.9.1)via 💠 default on ☁️  me(pdx) on ☁️   8 🐟
❯ ../starship/target/debug/starship prompt

# this is with this patch
~/p/ideas on  master [$?] via ⬢ v15.3.0 via 🐍 v3.9.1 (python-3.9.1) via 💠 default on ☁️  me(pdx) on ☁️   8 🐟
❯ ⏎

```

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

File: src/configs/python.rs [hunk 1]
```diff
@@ -21,7 +21,7 @@ impl<'a> RootModuleConfig<'a> for PythonConfig<'a> {
             pyenv_prefix: "pyenv ",
             python_binary: VecOr(vec!["python", "python3", "python2"]),
             scan_for_pyfiles: true,
-            format: "via [${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\))]($style)",
+            format: "via [${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\))]($style) ",
```
Comment (andytom) [inline src/configs/python.rs:24]: I think this should be

```suggestion
            format: "via [${symbol}${pyenv_prefix}(${version} )(\\($virtualenv\\) )]($style)",
```
Otherwise there would be too many spaces if the virtualenv is not activated but there is a python file.

**Review by andytom — COMMENTED** [review]
Thanks for fixing this @offbyone, I have left a suggestion, can you also update the tests and the documentation (you only need to update the English version the rest will be done automatically).

File: src/configs/python.rs (hunk 1 above)
Comment (offbyone) [reply src/configs/python.rs:24]: Can do!

**Comment by offbyone** [comment]
The test that fails passed in the last run, which differs only in its commit message. I'm pretty sure that this was a nondeterministic test run.

**Comment by chipbuster** [comment]
> The test that fails passed in the last run, which differs only in its commit message. I'm pretty sure that this was a nondeterministic test run.

Yeah, we've been fighting issues with that on-and-off for the last year. The only environments the race conditions have appeared in are GitHub Action and an s390x, which has on the order of 300 threads of actual parallelism.

I've restarted a test run for you.

**Comment by andytom** [comment]
Hi @offbyone, there have been some changes to the python module that means that there are some merge conflicts would you be able to fix them? Also can you update the default format string in the [docs](https://github.com/starship/starship/tree/master/docs/config#python)?

**Comment by ericbn** [comment]
I don't see other modules having to add a space before of after them. This should not be handled by the modules, but by how spaceship joins them together.

**Comment by ericbn** [comment]
@offbyone, do you plan to update your PR? I'm more than happy to help rebasing the changes and also updating the docs accordingly.

**Comment by offbyone** [comment]
Yeah, I plan to rebase it, sorry -- Real Life™ has interfered.

**Comment by offbyone** [comment]
@ericbn I have rebased it; is this mergeable now?

**Comment by andytom** [comment]
> @ericbn I have rebased it; is this mergeable now?

The only thing that is missing that I can see is to update the English version of the [docs](https://github.com/starship/starship/tree/master/docs/config#python). Other than that we should be good to go.

**Comment by offbyone** [comment]
There we go: docs updated too.

**Review by vladimyr — APPROVED** [review]
LGTM 👍

**Comment by offbyone** [comment]
Would someone with permissions care to merge this?
