### PR TITLE
fix: Don't print the first module prefix after a line-break

### LINKED ISSUE #461: Don't show the prefix of the first module after the `line_break`
#### Current Behavior

Currently, the first module after the `line_break` module will have its prefix visible. This makes the new line start with a prefix, which I think looks worse than it would without the prefix:

image

This is what the prompt looks like with just the `time` module enabled:
```toml
[time]
disabled = false
```

#### Expected Behavior

Similarly to how the first prefix in the prompt doesn't appear, neither should the first prefix after a `line_break` module.

#### Possible Solution

The implementation that hides the first prefix can be found here:
https://github.com/starship/starship/blob/master/starship/src/print.rs#L46-L50

Maybe similar logic should be implemented following after the `line_break` module is printed.

### PR DESCRIPTION
**Pull request by pt2121**
#### Description
Not show the prefix of the first module of the 2nd line.
I'd never used Rust before - not sure if there is any more elegant way to do this so feedback is welcome.

#### Motivation and Context
Closes #461

#### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Screenshots (if appropriate):

Screen Shot 2019-10-02 at 7 57 59 PM

#### How Has This Been Tested?
I config'ed my prompt to have 2 lines and made sure the prefixes of the 1st modules not show up.

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

File: src/print.rs [hunk 1]
```diff
@@ -49,7 +49,18 @@ pub fn prompt(args: ArgMatches) {
         write!(handle, "{}", module_without_prefix).unwrap()
     }
 
-    // Print all remaining modules
+    while let Some(module) = printable.next() {
+        write!(handle, "{}", module).unwrap();
+        if module.to_string().contains('\n') {
```
Comment (matchai) [inline src/print.rs]: I think a slightly more robust and declarative way to handle this would be to check the module's name, rather than its string representation. 🙂

Comment (pt2121) [reply src/print.rs]: Thanks for your review. updated!

I'll squash commits later if you prefer that.

File: src/print.rs [hunk 2]
```diff
@@ -41,16 +41,19 @@ pub fn prompt(args: ArgMatches) {
         .flatten()
         .collect::<Vec<Module>>(); // Remove segments set to `None`
 
+    let mut line_break = true;
```
Comment (matchai) [inline src/print.rs]: I think this may be a better variable name, since it's not only to do with the `line_break` module.

```suggestion
	// Skip printing the prefix of the first module
    let mut print_without_prefix = true;
```

Comment (pt2121) [reply src/print.rs]: very good point. updated!

**Comment by pt2121** [comment]
Awesome, thanks for this good looking prompt and patiently reviewing my PR!

**Comment by matchai** [comment]
@all-contributors Please add @pt2121 for code. 😄
