### PR TITLE
fix: remove errant whitespace which broke tar command

### LINKED ISSUE #1313: Install fails on Ubuntu 20.04 (x64)
#### Current Behavior

When running the following command `curl -fsSL https://starship.rs/install.sh | bash` the install fails due to "Starship not yet supporting your configuration."
#### Expected Behavior

Starship is expected to install as normal.

#### Additional context/Screenshots

```sh
> Installing Starship, please wait…
tar (child): : Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

x Command failed (exit code 23): curl --silent --fail --location https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz

> This is likely due to Starship not yet supporting your configuration.
> If you would like to see a build for your configuration,
> please create an issue requesting a build for x86_64-unknown-linux-gnu:
> https://github.com/starship/starship/issues/new/\n
```

#### Possible Solution

The problem seems to be here: https://github.com/starship/starship/blob/master/install/install.sh#L82

Running the following command:

```sh
curl --fail --location "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
```

Returns the the following:

```sh
❯ curl --fail --location "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
Warning: Binary output can mess up your terminal. Use "--output -" to tell 
Warning: curl to output it to your terminal anyway, or consider "--output 
Warning: <FILE>" to save to a file.

```

Adding the `-O` flag, resolves the issue.

```sh
curl --silent --fail --location "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz" -O
``

#### Environment
- Starship version: 0.42.0
- bash version: GNU bash, version 5.0.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
- Operating system: Ubuntu 20.04
- Terminal emulator: <unknown terminal> <unknown version>

#### Relevant Shell Configuration

```bash
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
#if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
#    . /etc/bash_completion
#fi

eval "$(starship init bash)"
```

#### Starship Configuration

```toml
<unknown config>
```

### PR DESCRIPTION
**Pull request by chipbuster**
#### Description

HOTFIX: curl installer will be broken until this is merged.

There was a space added to a tar command in #1305. While it seems innocuous, it causes tar to either try to extract the file `"v"` or the file `""` instead of reading from stdin like we want. This reverts that change by putting the `VERBOSE` invocation in the middle of the command string, hopefully making it more obvious if it breaks in the future.

Curiously, this did *not* break the script when executing it directly (`./install.sh`) but *did* break it when running it in a new shell (`bash install.sh`). I've determined that that has something to do with the environment, but haven't worked out anything deeper than that.

#### Motivation and Context

Closes #1313

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

File: install/install.sh [hunk 1]
```diff
@@ -114,7 +114,7 @@ fetch_and_unpack() {
   # I'd like to separate this into a fetch() and unpack() function, but I can't
   # figure out how to get bash functions to read STDIN/STDOUT from pipes
   if [ "${EXT}" = "tar.gz" ]; then
-    fetch "${URL}" | ${sudo} tar xzf "${VERBOSE}" - -C "${BIN_DIR}"
+    fetch "${URL}" | ${sudo} tar xz"${VERBOSE}"f - -C "${BIN_DIR}"
```
Comment (vladimyr) [inline install/install.sh:117]: Damn, I really messed it up, sorry 🤦 
Btw, maybe we can make it even more obvious:
```suggestion
    fetch "${URL}" | ${sudo} tar -xz"${VERBOSE}"f - -C "${BIN_DIR}"
```

Comment (chipbuster) [reply install/install.sh:117]: Nah, I was the reviewer there, the onus is on me. (Also, I'm a maintainer, making that doubly true).

So I don't know if this is still true, but back when I was first learning command line shenanigans a decade ago, I found that adding a `-` to tar options made them more order-sensitive, sometimes in ways that didn't agree with each other on different platforms.

Do we know that this problem no longer exists? Or perhaps it's an issue that I entirely imagined?

Comment (chipbuster) [reply install/install.sh:117]: As a simple example, `tar fxvz file.tgz` works on my system, while `tar -fxvz file.tgz` generates 
```
tar: You must specify one of the '-Acdtrux', '--delete' or '--test-label' options
Try 'tar --help' or 'tar --usage' for more information.
```

Comment (vladimyr) [reply install/install.sh:117]: I think `-f` needs to come last: `tar -xvzf` because that is the only one that receives argument. Does that work?

Comment (chipbuster) [reply install/install.sh:117]: Yes, I'm just not sure how that works on other platforms.

I guess another way to think of the question is this: can we think of a value of VERBOSE that will break the dashless form in a bad way (e.g. extracting the wrong file, passing inadvertent flags to `tar`) but won't break the dash form?

Comment (vladimyr) [reply install/install.sh:117]: > Yes, I'm just not sure how that works on other platforms.

Which platform you have? If this works on a Mac (I tested it, it does) it will work on other BSDs. The only other case would be GNU `tar` which I believe is fully backward compatible with BSD implementation.

> I guess another way to think of the question is this: can we think of a value of VERBOSE that will break the dashless form in a bad way (e.g. extracting the wrong file, passing inadvertent flags to tar) but won't break the dash form?

Well, that is a really hard question to answer... I guess we are a bit safer with dashed form because anything before `-f` would be treated as a flag, assuming that bad flag is better than operating on a bad file...

**Comment by grimm26** [comment]
it would also be explicit to put a `--output -` with the curl command that is equivalent to the `-O-` on the wget command.
