### PR TITLE
fix(git_status): show working tree status if index status is present

### LINKED ISSUE #2937: Git status: modified files are not shown if also staged
#### Current Behavior
When a file is both modified and staged, it will only be dis played as « staged ».

#### Expected Behavior
Take the file into account both in « staged » and « modified » 

##### Git status of repo

When already present file is modified:

```
❯ git -C /home/mmillet/test --no-optional-locks status  --porcelain=2 --branch
# branch.oid 72870ff32e67c8d9c1da4df4550182418ee70675
# branch.head master
1 MM N... 100644 100644 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 72943a16fb2c8f38f9dde202b7a70ccc19c52f34 test1
1 .M N... 100644 100644 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 test2
1 AM N... 000000 100644 100644 0000000000000000000000000000000000000000 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 test3

000000000000000000 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 test3
```

`test1` was already in previous commit, and has been modified, added, and modified again
`test2` was already in previous commit, then modified
`test3` just added, then modified

When in this state, my indicator show only one added file :`test2` (if `test2` is not modified I do not see any file as modified). 

Starship debug (I removed config since it's displayed at the bottom of the issue):
```
❯ env STARSHIP_LOG=trace starship module git_status
[DEBUG] - (starship::config): STARSHIP_CONFIG is not set
[DEBUG] - (starship::config): Using default config path: /home/mmillet/.config/starship.toml
[TRACE] - (starship::utils): Trying to read from "/home/mmillet/.config/starship.toml"
[TRACE] - (starship::utils): File read sucessfully
[TRACE] - (starship::config): Config file content: "
...
"
[DEBUG] - (starship::config): Config parsed: Table({"format": String("$username$hostname$shlvl$directory$git_branch$git_commit$git_state$git_status$hg_branch$docker_context$package$nodejs$ocaml$python$conda$memory_usage$aws$cmd_duration$line_break$jobs$battery$time$status$character"), "hostname": Table({"format": String("[$hostname]($style) | "), "ssh_only": Boolean(false)}), "directory": Table({"truncate_to_repo": Boolean(false), "fish_style_pwd_dir_length": Integer(2)}), "username": Table({"format": String("[$user]($style) | ")}), "git_status": Table({"style": String("bold cyan"), "ahead": String("↑${count}"), "diverged": String("↑${ahead_count}↓${behind_count}"), "behind": String("↓${count}"), "conflicted": String("✖${count}(red)"), "untracked": String("[…\u{200d}$count](244)"), "modified": String("✚$count(bold blue)"), "staged": String("[●$count](bold bright-yellow)"), "renamed": String("»(green)"), "deleted": String("✘(red)")})})
[DEBUG] - (starship::config): Config found for "git_status": Some(Table({"style": String("bold cyan"), "ahead": String("↑${count}"), "diverged": String("↑${ahead_count}↓${behind_count}"), "behind": String("↓${count}"), "conflicted": String("✖${count}(red)"), "untracked": String("[…\u{200d}$count](244)"), "modified": String("✚$count(bold blue)"), "staged": String("[●$count](bold bright-yellow)"), "renamed": String("»(green)"), "deleted": String("✘(red)")}))
[DEBUG] - (starship::modules::git_status): New repo status created
[TRACE] - (starship::utils): Executing command "git" with args ["-C", "/home/mmillet/test", "--no-optional-locks", "status", "--porcelain=2", "--branch"]
[TRACE] - (starship::utils): Executing command "git" with args ["-C", "/home/mmillet/test", "--no-optional-locks", "stash", "list"]
[TRACE] - (starship::utils): Using "/usr/bin/git" as "git"
[TRACE] - (starship::utils): Using "/usr/bin/git" as "git"
[TRACE] - (starship::utils): stdout: "# branch.oid 72870ff32e67c8d9c1da4df4550182418ee70675\n# branch.head master\n1 MM N... 100644 100644 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 72943a16fb2c8f38f9dde202b7a70ccc19c52f34 test1\n1 .M N... 100644 100644 100644 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 test2\n1 AM N... 000000 100644 100644 0000000000000000000000000000000000000000 e69de29bb2d1d6434b8b29ae775ad8c2e48c5391 test3\n", stderr: "", exit code: "Some(0)", took 3.761845ms
[TRACE] - (starship::config): Parsing color_string: bright-yellow
[TRACE] - (starship::config): Read predefined color: bright-yellow
[TRACE] - (starship::utils): stdout: "", stderr: "", exit code: "Some(0)", took 4.6319ms
[TRACE] - (starship::config): Parsing color_string: cyan
[TRACE] - (starship::config): Read predefined color: cyan
[TRACE] - (starship::modules): Took 7.221036ms to compute module "git_status"
[✚1●2] ⏎                
```

#### Environment
- Starship version: 0.56.0
- fish version: fish, version 3.1.0
- Operating system: Ubuntu 20.04
- Terminal emulator: <unknown terminal> <unknown version>
- Git Commit Hash: f64cfa6a
- Branch/Tag: v0.56.0
- Rust Version: rustc 1.53.0 (53cb7b09b 2021-06-17)
- Rust channel:  release
- Build Time: 2021-07-13 22:05:04
#### Relevant Shell Configuration

```bash
set -x PATH .local/bin $PATH

starship init fish | source
```

#### Starship Configuration

```toml
format = """
$username\
$hostname\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$nodejs\
$ocaml\
$python\
$conda\
$memory_usage\
$aws\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$character"""

[hostname]
format = "[$hostname]($style) | "
ssh_only = false

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 2

[username]
format = "[$user]($style) | "

[git_status]
style= "bold cyan"
ahead = "↑${count}"
diverged = "↑${ahead_count}↓${behind_count}"
behind = "↓${count}"
conflicted = "✖${count}(red)"
untracked = "[…‍$count](244)"
modified = "✚${count}(bold blue)"
staged = '[●$count](bold bright-yellow)'
renamed = "»(green)"
deleted = "✘(red)"

```

### PR DESCRIPTION
**Pull request by EliaGeretto**
#### Description
This PR modifies the parser for the output of the `git` command in the `git_status` module. It ensures that, even when an index status is present or the file has been copied/renamed, the working tree status is correctly parsed and displayed in the prompt. This does not apply to merge conflict situations, in which only the merge conflict indicator is shown, as before.

#### Motivation and Context

This PR closes #2937.

In addition, files that were both renamed and modified were only shown as renamed, but not as modified.

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [X] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [X] I have updated the tests accordingly.

### CODE REVIEW

File: src/modules/git_status.rs [hunk 1]
```diff
@@ -230,43 +230,46 @@ struct RepoStatus {
...
-        self.untracked += Self::is_untracked(s) as usize;
+        match s.chars().next().unwrap() {
+            '1' => self.parse_normal_status(&s[2..4]),
+            '2' => {
+                self.renamed += 1;
+                self.parse_normal_status(&s[2..4])
+            }
+            'u' => self.conflicted += 1,
+            '?' => self.untracked += 1,
+            _ => panic!("git_status: unknown line type"),
```
Comment (andytom) [inline src/modules/git_status.rs:271]: Rather than unwrapping here it would be better to include it in the match, something like (I am on my phone so this might not be completely correct) 
```suggestion
        match s.chars().next() {
           Some('1') => self.parse_normal_status(&s[2..4]),
           Some('2') => {
                self.renamed += 1;
                self.parse_normal_status(&s[2..4])
            }
            Some('u') => self.conflicted += 1,
            Some('?') => self.untracked += 1,
            _ => panic!("git_status: unknown line type"),
```

Comment (andytom) [inline src/modules/git_status.rs:271]: Rather than panicking here it would be better to log an error.

**Review by andytom — CHANGES_REQUESTED** [review]
Thank you for your contribution @EliaGeretto, I have left some suggestions to make the code a bit more robust but other than that this looks OK so far.

**Comment by EliaGeretto** [comment]
The logic behind panicking was that an error in those two cases indicates a programming error somewhere, because the `git status --porcelain=2` format is defined and guaranteed not to change. Anyway, I have updated the commit to avoid panicking on a parsing error and, instead, write to the log. I also realized that I was not handling the `!` line type, which should not show, but is still valid, so I added it as a case to the `match`.

File: src/modules/git_status.rs [hunk 2]
```diff
@@ -230,43 +230,51 @@ struct RepoStatus {
...
+                    self.parse_normal_status(&s[2..4])
+                }
+                'u' => self.conflicted += 1,
+                '?' => self.untracked += 1,
+                '!' => (),
+                _ => log::error!("Unknown line type in git status output"),
+            }
+        } else {
+            log::error!("Missing line type in git status output");
+        }
```
Comment (andytom) [inline src/modules/git_status.rs:277]: Not a blocker but I think the if let can be removed from here
```suggestion
           match s.chars().next() {
              Some('1') => self.parse_normal_status(&s[2..4]),
              Some('2') => {
                  self.renamed += 1;
                  self.parse_normal_status(&s[2..4])
              }
              Some('u') => self.conflicted += 1,
              Some('?') => self.untracked += 1,
              Some('!') => (),
              Some(_) => log::error!("Unknown line type in git status output"),
              _ => log::error!("Missing line type in git status output"),
             }
```

**Review by andytom — APPROVED** [review]
Have left a little suggestion but other than that I think this is ok

**Comment by andytom** [comment]
> The logic behind panicking was that an error in those two cases indicates a programming error somewhere, because the `git status --porcelain=2` format is defined and guaranteed not to change. Anyway, I have updated the commit to avoid panicking on a parsing error and, instead, write to the log. I also realized that I was not handling the `!` line type, which should not show, but is still valid, so I added it as a case to the `match`. I also added a test case that verifies that ignored files are not shown.

In general we try to avoid panics whenever we can as that will cause starship to not output anything which means that the user doesn't get a prompt which is a very bad user experience, while the output of `git status --porcelain=2` should never change there is always the possibility that something else causes the output to get mangled (e.g a wrapper script around git) so we always try to be defensive in these sorts of situations.

**Comment by EliaGeretto** [comment]
I have applied the modification requested in the comment, formatted and squashed. The PR should be ready to be merged.

**Comment by andytom** [comment]
Thank you for your contribution @EliaGeretto.
