### PR TITLE
fix: Prevent `rust` module from installing toolchains

### LINKED ISSUE #417: The `rust` module causes `rustup install`
#### Current Behavior

When ~~`rust-toolchain` exists in `.` or any parent directory  and the target toolchain is not installed~~ the toolchain [specified with `$RUST_TOOLCHAIN`, `rustup override`, or `rust-toolchain`](https://github.com/rust-lang/rustup.rs/tree/47faf31402f1f2d727461a52db599915416ad061#override-precedence) is not installed, the `rust` module (or rather, `rustc --version`) starts installing the toolchain without any terminal output. It looks as if `starship` is hanging.

```
sampleapp is 📦 v0.1.0 via Rust v1.37.0
❯ rustc +beta --version
error: toolchain 'beta-x86_64-unknown-linux-gnu' is not installed

sampleapp is 📦 v0.1.0 via Rust v1.37.0
❯ date
Tue 24 Sep 2019 10:02:12 PM JST

sampleapp is 📦 v0.1.0 via Rust v1.37.0
❯ echo beta > ./rust-toolchain

sampleapp is 📦 v0.1.0 via Rust v1.38.0-beta.7
❯ date
Tue 24 Sep 2019 10:08:07 PM JST

sampleapp is 📦 v0.1.0 via Rust v1.38.0-beta.7
❯ rustc +beta --version
rustc 1.38.0-beta.7 (1c653259d 2019-09-21)
```

#### Expected Behavior

At least, shell prompts should not download large data without confirmation.

#### Additional context/Screenshots

This is the situation I encountered first.

```
~/src
❯ git clone https://github.com/libra/libra --depth 1
Cloning into 'libra'...
remote: Enumerating objects: 2003, done.
remote: Counting objects: 100% (2003/2003), done.
remote: Compressing objects: 100% (1871/1871), done.
remote: Total 2003 (delta 219), reused 856 (delta 80), pack-reused 0
Receiving objects: 100% (2003/2003), 3.35 MiB | 392.00 KiB/s, done.
Resolving deltas: 100% (219/219), done.

~/src took 12s
❯ ./libra

~/src took 12s
❯ # ??? (Pressed Ctrl-C)

~/src took 12s
❯ pwd
/home/ryo/src/libra

~/src took 12s
❯ # what is happening????????????
```

#### Environment
- Starship version: ~~`starship 0.17.0`~~ → `starship 0.18.0`
- Shell type: zsh & tmux
- Shell version: `zsh 5.7.1 (x86_64-pc-linux-gnu)`, `tmux 2.9a`
- Shell plugin manager: zplug
- Terminal emulator: Alacritty
- Operating system: Linux 4.19.73-1-lts (Arch Linux)

#### Relevant Shell Configuration

[`~/.zshrc`](https://github.com/qryxip/dotfiles/blob/11bfbb94511ef7512e193a7f5724dc6a80dc5f2a/common/home/.zshrc#L33)
[`~/.tmux.conf`](https://github.com/qryxip/dotfiles/blob/11bfbb94511ef7512e193a7f5724dc6a80dc5f2a/common/home/.tmux.conf)

#### Starship Configuration

```toml
[directory]
truncation_length = 0

[rust]
symbol = "Rust "
```

#### Possible Solution

[Current implementation](https://github.com/starship/starship/blob/c9878cab69cca791f92544ffdc66f1b57c0c679a/src/modules/rust.rs#L42-L54)

~~1. Check if `./rust-toolchain` exists.
1.1. If `./rust-toolchain` does not exist, just execute `rustc --version` as usual.
2. Otherwise, execute `rustc +"$(cat ./rust-toolchain)" --version`.
3. If the command failed, display `"Not Installed (rust-toolchain = {:?})"` or something.~~

~~1. Check if `./rust-toolchain` exists.
1.1. If not, just execute `rustc --version` as usual.
2. Otherwise, check if `rustup toolchain list` contains the content of `./rust-toolchain`
2.1. If `rustup` is not in `$PATH`, we can `rustc --version` safely.
3. If the target toolchain is not installed, display `"Not Installed (rust-toolchain = {:?})"` or something.~~

~~1. Execute `rustup toolchain list` to get information of installed toolchains and default toolchain.
1.1. If `rustup` is not in `$PATH`, we can `rustc --version` safely.
2. If `rust-toolchain` is found, check if `rustup_toolchain_list.contains(rust_toolchain)`
2.1. If the target toolchain is not installed, display `"Not Installed (rust-toolchain = {:?})"` or something.
2.2. If `rust-toolchain` is not found and ["no default toolchain configured"](https://stackoverflow.com/questions/44303915/no-default-toolchain-configured-after-installing-rustup), Display `"No default toolchain"` or something.
3. Parse the output of `rustc +"$default_or_specified_toolchain" --version`.~~

[I forgot `RUST_TOOLCHAIN` and `rustup override`.](https://github.com/rust-lang/rustup.rs/tree/47faf31402f1f2d727461a52db599915416ad061#override-precedence)

1. Find the toolchain override.
1.1. If no override found, just execute `rustc --version` as usual.
2. Parse the output of `rustup run "$toolchain" rustc --version`.
2.1. If `rustup` is not in `$PATH`, execute `rustc --version`.
2.2. If `rustup` command failed, display the error message trimming the first `"error: "`.

### PR DESCRIPTION
**Pull request by qryxip**
#### Description

Prevent `rust` module from installing the toolchain [specified with `$RUSTUP_TOOLCHAIN`, `rustup override set`, or `rustup-toolchain`](https://github.com/rust-lang/rustup.rs/tree/924630ba1162b81c0421e8ce56968d4984c605a4#override-precedence) when it is not installed.

#### Motivation and Context

Closes #417.

#### Types of changes

- Displays ~~error of `rustup run _ rustc --version` (`"toolchain '_' is not installed"`)~~ toolchain names when they are not installed.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Screenshots (if appropriate):
screenshot

#### How Has This Been Tested?

- [ ] I have tested using **MacOS**
- [x] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

~~Nothing to update.~~ Added tests but I didn't modify the existing tests.

- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

File: src/modules/rust.rs [hunk 1]
```diff
@@ -19,27 +23,85 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
+fn execute_rustup_override_list(cwd: &Path) -> Option<String> {
+    let Output { stdout, .. } = Command::new("rustup")
+        .args(&["override", "list"])
+        .output()
+        .ok()?;
+    let stdout = String::from_utf8(stdout).ok()?;
+    if stdout == "no overrides\n" {
+        return None;
+    }
+    stdout
```
Comment (nickwb) [inline src/modules/rust.rs]: Would be great to move this `stdout` parsing logic in to another function, where we could write a test or two against it?

File: src/modules/rust.rs [hunk 2]
```diff
@@ -19,27 +23,85 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
+            let dir = words.next()?;
+            let toolchain = words.next()?;
+            Some((dir, toolchain))
+        })
+        .find(|(dir, _)| cwd.starts_with(dir))
+        .map(|(_, toolchain)| toolchain.to_owned())
+}
+
+fn find_rust_toolchain_file(mut dir: &Path) -> Option<String> {
+    loop {
```
Comment (nickwb) [inline src/modules/rust.rs]: Should we limit the maximum depth here to some small reasonable number? Though I realise this will potentially compromise accuracy..

File: src/modules/rust.rs [hunk 3]
```diff
@@ -19,27 +23,85 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
+        let path = dir.join("rust-toolchain");
+        if path.exists() {
```
Comment (nickwb) [inline src/modules/rust.rs]: For the first iteration: we could consider use the cached data from `context.get_dir_files()` and `find()` rather than hitting the OS again.

This code is simpler though, so it's probably worth measuring...

File: src/modules/rust.rs [hunk 4]
```diff
@@ -19,27 +23,85 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
+fn execute_rustup_run_rustc_version(toolchain: &str) -> Result<String, String> {
+    let output = Command::new("rustup")
+        .args(&["run", toolchain, "rustc", "--version"])
+        .output()
+        .map_err(|e| e.to_string())?;
+    if output.status.success() {
+        String::from_utf8(output.stdout).map_err(|e| e.to_string())
+    } else {
+        let stderr = String::from_utf8(output.stderr).map_err(|e| e.to_string())?;
+        Err(if stderr.starts_with("error: ") {
```
Comment (nickwb) [inline src/modules/rust.rs]: Would `trim_start_matches()` work better here?

File: src/modules/rust.rs [hunk 5]
```diff
@@ -19,27 +23,85 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
+
+fn execute_rustup_run_rustc_version(toolchain: &str) -> Result<String, String> {
+    let output = Command::new("rustup")
+        .args(&["run", toolchain, "rustc", "--version"])
+        .output()
+        .map_err(|e| e.to_string())?;
+    if output.status.success() {
+        String::from_utf8(output.stdout).map_err(|e| e.to_string())
+    } else {
+        let stderr = String::from_utf8(output.stderr).map_err(|e| e.to_string())?;
```
Comment (nickwb) [inline src/modules/rust.rs]: I'm personally not a huge fan of the long error in the prompt. Can we throw in some config to toggle this? Perhaps we could hide the whole module if this fails, or perhaps a single "alert" symbol to indicate something is wrong but without saying what.

**Comment by nickwb** [comment]
I did a very quick smoke test on Windows and confirmed that all seemed to be working as expected.

File: src/modules/rust.rs (hunk 1 above)
Comment (qryxip) [reply src/modules/rust.rs]: Right. I moved the part to `extract_toolchain_from_rustup_override_list` and added a test for it.

File: src/modules/rust.rs (hunk 4 above)
Comment (qryxip) [reply src/modules/rust.rs]: I removed the part.

File: src/modules/rust.rs (hunk 5 above)
Comment (qryxip) [reply src/modules/rust.rs]: Now it displays toolchain name (`channel-triple`). I updated the screenshot.

File: src/modules/rust.rs (hunk 3 above)
Comment (qryxip) [reply src/modules/rust.rs]: Used `Context::get_dir_files` for the first iteration.

File: src/modules/rust.rs (hunk 2 above)
Comment (qryxip) [reply src/modules/rust.rs]: I don't think this degrades the performance. Its behavior is the same as [`~/.cargo/bin/rustc --version`](https://github.com/rust-lang/rustup.rs/blob/d84e6e50126bccd84649e42482fc35a11d019401/src/config.rs#L320-L358
).

File: src/modules/rust.rs (hunk 5 above)
Comment (nickwb) [reply src/modules/rust.rs]: Great!

File: src/modules/rust.rs (hunk 2 above)
Comment (nickwb) [reply src/modules/rust.rs]: My benchmarks suggests this is about 30% slower. That said, I think it is quick enough - under 100ms on most systems and under 50ms on systems with fast I/O.

**Comment by chipbuster** [comment]
One minor request: can we leave a comment in the code explaining why we do this? I can imagine someone coming along in the future and wondering why we do this seemingly-roundabout way of resolving the version.

**Comment by qryxip** [comment]
Oh Rust 1.38.0 was released and `rustfmt` changed the rule.
https://github.com/starship/starship/pull/426/checks?check_run_id=237892684

File: src/modules/rust.rs [hunk 6]
```diff
@@ -19,27 +24,137 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
         return None;
     }
 
-    match get_rust_version() {
-        Some(rust_version) => {
-            const RUST_CHAR: &str = "🦀 ";
+    // `$CARGO_HOME/bin/rustc(.exe) --version` may attempt installing a rustup toolchain.
```
Comment (nickwb) [inline src/modules/rust.rs]: Excellent detail in this comment! 💯

**Comment by qryxip** [comment]
@chipbuster Is the merge commit is necessary? I had rebased to include #432...

**Comment by chipbuster** [comment]
@qryxip Our GitHub is set up so that merges to master must be fast-forward merges, so if master ever gets ahead of a PR, we need to merge or rebase at some point to be able to merge the PR.

**Comment by qryxip** [comment]
@chipbuster I got it. Then may I remove the merge commit and rebase again? We have to re-run CI either way since one of the jobs failed with "network request" error.

**Comment by chipbuster** [comment]
Something that's worked for us in the past is to create an empty commit which shadows the HEAD (just for the purpose of re-triggering CI). You can do that with `git commit --allow-empty` and then writing a simple commit message, then pushing that. We squash all PRs on merge anyways, so it won't show up in `master`.

If that still fails, feel free to do whatever you need to do to get it working.

**Comment by qryxip** [comment]
> We squash all PRs on merge anyways

That's true. `master` does not contain any merge commit. I will add a empty commit.

**Comment by chipbuster** [comment]
@qryxip Thanks so much for the PR! This looks like it was a fair bit of work to get right.

@all-contributors Please add @qryxip for an excellent code contribution.
