### PR TITLE
fix(shell): Support conditional format strings for `$indicator`

### LINKED ISSUE #2474: shell module doesn't support conditional format strings
#### Current Behavior

The shell module doesn't seem to support conditional format strings, e.g.:

```toml
[shell]
fish_indicator = ""
bash_indicator = "🐚"
format = "($indicator )"
disabled = false
```

Nothing displays for bash or fish. Removing the `format = ...` line displays: ` ❯` for fish (note the space) and `🐚  ❯` for bash.

#### Expected Behavior

`🐚  ` shows up for bash and nothing shows up for fish.

#### Additional context/Screenshots

Test cases to add to the `shell` module:

```rust
    #[test]
    fn test_custom_format_optional_indicator_match() {
        let expected = Some(format!("{} ", "B"));
        let actual = ModuleRenderer::new("shell")
            .shell(Shell::Bash)
            .config(toml::toml! {
                [shell]
                bash_indicator = "B"
                format = "($indicator )"
                disabled = false
            })
            .collect();

        assert_eq!(expected, actual);
    }

    #[test]
    fn test_custom_format_optional_indicator_no_match() {
        let expected = None;
        let actual = ModuleRenderer::new("shell")
            .shell(Shell::Fish)
            .config(toml::toml! {
                [shell]
                bash_indicator = "B"
                format = "($indicator )"
                disabled = false
            })
            .collect();

        assert_eq!(expected, actual);
    }
```

#### Environment
- Starship version: 0.50.0
- bash version: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.
- Operating system: Mac OS 10.15.7
- Terminal emulator: Apple_Terminal 433
- Git Commit Hash: 3a4c9063
- Branch/Tag: master
- Rust Version: rustc 1.50.0
- Rust channel:  release
- Build Time: 2021-03-18 09:54:54

### PR DESCRIPTION
**Pull request by rouge8**
#### Motivation and Context

Previously attempting to use conditional format strings with `$indicator` would never display an indicator, e.g.:

```toml
[shell]
fish_indicator = ""
bash_indicator = "B "
format = "($indicator )"
disabled = false
```

This would always display an empty string. With this patch, this displays `B ` on bash and nothing on fish, as intended.

Closes #2474.

#### How Has This Been Tested?

- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

File: src/modules/shell.rs [hunk 1]
```diff
@@ -28,6 +28,16 @@ pub fn module<'a>(context: &'a Context) -> Option<Module<'a>> {
...
+            .map(|var| match var {
+                "bash_indicator" => Some(Ok(config.bash_indicator)),
+                "fish_indicator" => Some(Ok(config.fish_indicator)),
+                "zsh_indicator" => Some(Ok(config.zsh_indicator)),
+                "powershell_indicator" => Some(Ok(config.powershell_indicator)),
+                "ion_indicator" => Some(Ok(config.ion_indicator)),
+                "elvish_indicator" => Some(Ok(config.elvish_indicator)),
+                "tcsh_indicator" => Some(Ok(config.tcsh_indicator)),
+                _ => None,
+            })
```
Comment (rouge8) [inline src/modules/shell.rs:40]: It seems like there should be a better way to do this, but I'm in a little over my head. Very open to better ideas!

Comment (vladimyr) [reply src/modules/shell.rs:40]: Hmm, yeah it is repetitive and verbose but it might just be **the** way according to https://users.rust-lang.org/t/access-struct-attributes-by-string/17520/2

**Review by vladimyr — APPROVED** [review]
LGTM
