### PR TITLE
fix: Fixture repo will now clone and set git config locally

### LINKED ISSUE #300: Tests overwrite global git user.name and user.email
#### Current Behavior
~/.gitconfig gets edited
See dfade6d6298b52e04dc8622c676ac8174a900587

#### Expected Behavior
Don't edit anything in the HOME

#### Environment
starship master

#### Suggested fix
Use a temporary home for tests, maybe

### PR DESCRIPTION
**Pull request by wyze**
#### Description
The common function in the test suite will now clone the repo into the fixture directory, and then set the git config locally to that repo.

#### Motivation and Context
Closes #300

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?
- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:
- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

File: tests/testsuite/common.rs [hunk 1]
```diff
@@ -68,7 +61,19 @@ pub fn create_fixture_repo() -> io::Result<std::path::PathBuf> {
         ])
         .output()?;
 
-    Ok(fixture_repo_dir)
+    git2::Repository::clone(fixture_repo_dir.to_str().unwrap(), &repo_dir.as_path()).unwrap();
```
Comment (nickwb) [inline tests/testsuite/common.rs]: Fairly minor, but can these `unwraps` potentially be `?` or `match` statements?

**Comment by chipbuster** [comment]
Well...I fat-fingered my keyboard and accidentally punched in a git commit message before I was ready, but I think it still tells you the gist of what happened. Certainly seems like it would be less confusing to leave it in there than it would be to revert and apply the same patch with two more words in the commit message.

Anyways, @all-contributors let's add @nickwb for review!
