### PR TITLE
feat: Add `bug-report` sub-command

### LINKED ISSUE #31: Create pre-populated GitHub issues from starship directly
Already dreaming about features for v2.0. 😴💭 
@sirMerr had a great idea that I wanted to share with everyone! 

In order to do away with a lot of the headache associated with creating GitHub issues for bug reports, it would be pretty cool if we could pre-populate much of the issue based on the user's local installation.

When the user uses `starship bug-report`, a link will be generated with pre-populated fields for the following fields:
- OS
- Shell
- Plugin manager
- Shell configuration
- Starship configuration

Here's an example of how a pre-filled GitHub issue would look: [Example Link](https://github.com/starship/starship/issues/new?title=Bug%20Report:&body=%23%23+Bug+Report%0D%0A%0D%0A%23%23%23%23+Current+Behavior%0D%0A%3C%21--+A+clear+and+concise+description+of+the+behavior.+--%3E%0D%0A%0D%0A%23%23%23%23+Expected+Behavior%0D%0A%3C%21--+A+clear+and+concise+description+of+what+you+expected+to+happen.+--%3E%0D%0A%0D%0A%23%23%23%23+Additional+context%2FScreenshots%0D%0A%3C%21--+Add+any+other+context+about+the+problem+here.+If+applicable%2C+add+screenshots+to+help+explain.+--%3E%0D%0A%0D%0A%23%23%23%23+Environment%0D%0A-+Starship+version%3A+v1.0.0%0D%0A-+Shell+type%3A+Fish%0D%0A-+Shell+version%3A+fish%2C+version+3.0.1%0D%0A-+Shell+plugin+manager%3A+fisher+version+3.2.5%0D%0A-+Terminal+emulator%3A+iTerm2+v3.2.8%0D%0A-+Operating+system%3A+macOS+10.14.4%0D%0A%0D%0A%23%23%23%23+Relevant+Shell+Configuration%0D%0A%0D%0A%60%60%60bash%0D%0Asource+%7E%2F.config%2Ffish%2Falias.fish%0D%0Asource+%7E%2F.config%2Ffish%2Fpaths.fish%0D%0A%0D%0A%23+Source+secret+if+it+exists%0D%0Asourceadd+%7E%2F.config%2Ffish%2Fsecret.fish%0D%0A%0D%0A%23+Configure+Jump%0D%0Astatus+--is-interactive%3B+and+source+%28jump+shell+fish+%7C+psub%29%0D%0A%0D%0A%23+Load+all+saved+ssh+keys%0D%0A%2Fusr%2Fbin%2Fssh-add+-A+%5E%2Fdev%2Fnull%0D%0A%0D%0A%23+Set+the+emoji+width+for+iTerm%0D%0Aset+-g+fish_emoji_width+2%0D%0A%0D%0A%23+Hide+the+fish+greeting%0D%0Aset+fish_greeting+%22%22%0D%0A%0D%0A%23+Spacefish+config%0D%0Aset+-g+SPACEFISH_CHAR_SYMBOL+%E2%9D%AF%0D%0Aset+-g+SPACEFISH_EXEC_TIME_ELAPSED+2%0D%0Aset+-g+SPACEFISH_GIT_SYMBOL+%22%22%0D%0A%0D%0A%23+Use+legacy+fzf+keybindings%0D%0Aset+-g+FZF_LEGACY_KEYBINDINGS+1%0D%0A%0D%0A%23+Fish+syntax+highlighting%0D%0Aset+-g+fish_color_autosuggestion+%27555%27++%27brblack%27%0D%0Aset+-g+fish_color_cancel+-r%0D%0Aset+-g+fish_color_command+--bold%0D%0Aset+-g+fish_color_comment+red%0D%0Aset+-g+fish_color_cwd+green%0D%0Aset+-g+fish_color_cwd_root+red%0D%0Aset+-g+fish_color_end+brmagenta%0D%0Aset+-g+fish_color_error+brred%0D%0Aset+-g+fish_color_escape+%27bryellow%27++%27--bold%27%0D%0Aset+-g+fish_color_history_current+--bold%0D%0Aset+-g+fish_color_host+normal%0D%0Aset+-g+fish_color_match+--background%3Dbrblue%0D%0Aset+-g+fish_color_normal+normal%0D%0Aset+-g+fish_color_operator+bryellow%0D%0Aset+-g+fish_color_param+cyan%0D%0Aset+-g+fish_color_quote+yellow%0D%0Aset+-g+fish_color_redirection+brblue%0D%0Aset+-g+fish_color_search_match+%27bryellow%27++%27--background%3Dbrblack%27%0D%0Aset+-g+fish_color_selection+%27white%27++%27--bold%27++%27--background%3Dbrblack%27%0D%0Aset+-g+fish_color_user+brgreen%0D%0Aset+-g+fish_color_valid_path+--underline%0D%0A%60%60%60%0D%0A%0D%0A%23%23%23%23+Starship+Configuration%0D%0A%0D%0A%60%60%60bash%0D%0A%23+Default+configuration%0D%0A%60%60%60%0D%0A%0D%0A%23%23%23%23+Possible+Solution%0D%0A%3C%21---+Only+if+you+have+suggestions+on+a+fix+for+the+bug+--%3E)
By making use of the query params accepted by GitHub when creating new issues, we can make bug reporting _that_ much easier! 😄

### PR DESCRIPTION
**Pull request by jonstodle**
The `bug-report` sub command will automatically create and open a link to a pre-filled Github issue. Making it easier for users to report errors.

#### Description
This adds a sub command to generate the link. Information, such as operating system and it's version; the current shell's config; and current starship conf, is gathered from the environment and is included in the pre-filled text. The command will also try to open the link in the default browser. Should that fail it will print the link instead and ask the user to copy it.

This builds on the proposed changes in #225 

#### Motivation and Context
Makes it easier for users to report bugs, and easier to get the desired environment information.
Closes #31 

#### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### How Has This Been Tested?
There are some simple unit tests which only cover the basics. Apart from that it's manual testing.
- [x] I have tested using **MacOS**
- [ ] I have tested using **Linux**
- [ ] I have tested using **Windows**

#### Checklist:

- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by jonstodle** [comment]
We might want to add a section in the README mentioning this to make it disoverable

**Comment by johnletey** [comment]
@jonstodle Looks like Clippy is throwing an error 😄. Why don't you go and take a look: [log](https://github.com/starship/starship/runs/346642420#step:4:342), and make the appropriate changes.

**Comment by sirMerr** [comment]
I remember this :D -shifty eyes-. Thanks for tackling it 🙌!

**Comment by johnletey** [comment]
@jonstodle Sorry for taking over your PR 😄. Had some free time so thought I'd help you out!

I have gone ahead and fixed the Clippy errors. The tests are failing on the Windows run, not quite sure how to fix this.

**Comment by jonstodle** [comment]
No problem. We're working towards the same goal 👍

File: src/bug_report.rs [hunk 1]
```diff
@@ -0,0 +1,198 @@
...
+    let environment = Environment {
+        os_type: os_info.os_type(),
+        os_version: os_info.version().to_owned(),
+        shell_info: get_shell_info(),
+        starship_config: get_starship_config(),
+    };
+
+    let link = make_github_issue_link(crate_version!(), environment);
+
+    if open::that(&link)
```
Comment (matchai) [inline src/bug_report.rs]: Testing locally, this doesn't seem to work as expected. Despite the browser launching, the "unable to launch your browser" message still appears.

The following works for me though:
```rust
if open::that(&link).is_ok() {
    print!("Take a look at your browser. A GitHub issue has been populated with your configuration")
} else {
    println!(
        "I was unable to launch your browser. You'll have to copy this link instead:\n\n{}",
        link
    );
}
```

File: src/bug_report.rs [hunk 2]
```diff
@@ -0,0 +1,198 @@
...
+        .map(|exit_status| exit_status.success())
+        .unwrap_or(false)
+    {
+        println!(
+            "I was unable to launch your browser. You'll have to copy this link instead:\n\n{}",
+            link
```
Comment (matchai) [inline src/bug_report.rs]: The link ends up being pretty huge, filling up my entire terminal emulator. I think this would be a good time to use a [hyperlink](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) (or maybe generating a https://git.io/ shortened link 🤔 )

File: src/bug_report.rs [hunk 3]
```diff
@@ -0,0 +1,198 @@
...
+    os_type: os_info::Type,
+    os_version: os_info::Version,
+    shell_info: ShellInfo,
+    starship_config: String,
+}
+
+fn make_github_issue_link(starship_version: &str, environment: Environment) -> String {
+    let title = urlencoding::encode("Bug Report:");
+
+    let body = urlencoding::encode(&format!("## Bug Report
```
Comment (matchai) [inline src/bug_report.rs]: Given how many parameters there are, I think it would be a good idea to use [named parameters](https://doc.rust-lang.org/std/fmt/#named-parameters) to make future adjustments easier.

File: src/bug_report.rs [hunk 4]
```diff
@@ -0,0 +1,198 @@
...
+
+#### Relevant Shell Configuration
+
+```bash
+{}
+```
+
+#### Starship Configuration
+
+```bash
```
Comment (matchai) [inline src/bug_report.rs]: This definitely needs to be changed in the bug template, but we might as well fix it here too 😛 
```suggestion
```toml
```

**Comment by jonstodle** [comment]
Regarding the test, it's rather poor. As you mention, it's only going to work on *nix systems as you can "trick" it and override the location of the home directory. 

I think the best course of action is to either remove it or skip it on Windows (via a `#[cfg(not(windows))]` attribute)

File: src/bug_report.rs (hunk 1 above)
Comment (jonstodle) [reply src/bug_report.rs]: I just copied this wholesale

File: src/bug_report.rs (hunk 2 above)
Comment (jonstodle) [reply src/bug_report.rs]: I went with using git.io. It feels like a better solution, especially considering not all terminal emulators supporting hyperlinks (though I must admit support is impressive).

File: src/bug_report.rs [hunk 5]
```diff
@@ -0,0 +1,209 @@
...
+        let link = reqwest::Client::new()
+            .post(&format!("{}{}", GIT_IO_BASE_URL, "create"))
+            .form(&[("url", &link)])
+            .send()
+            .and_then(|mut response| response.text())
+            .map(|slug| format!("{}{}", GIT_IO_BASE_URL, slug))
+            .unwrap_or(link);
+
+        println!(
+            "I was unable to launch your browser. You'll have to copy this link instead:\n\n  {}",
```
Comment (matchai) [inline src/bug_report.rs]: I'd rather we don't call attention to being unable to launch the browser:
```suggestion
            "Click this link to create a GitHub issue populated with your configuration:\n\n  {}",
```

File: src/bug_report.rs [hunk 6]
```diff
@@ -0,0 +1,209 @@
...
+    os_type: os_info::Type,
+    os_version: os_info::Version,
+    shell_info: ShellInfo,
+    starship_config: String,
+}
+
+fn make_github_issue_link(starship_version: &str, environment: Environment) -> String {
+    let title = urlencoding::encode("Bug Report:");
+
+    let body = urlencoding::encode(&format!("## Bug Report
```
Comment (matchai) [inline src/bug_report.rs]: Here's a nice header for folks who have used this feature:

```suggestion
    let body = urlencoding::encode(&format!("<!--
┌────────────────────────────────────────────────────────────────────────┐
│                                                                        │
│   This issue has been pre-populated with your system's configuration   │
│               ♥ Thank you for submitting a bug report ♥                │
│                                                                        │
└────────────────────────────────────────────────────────────────────────┘
-->

## Bug Report
```

**Comment by jonstodle** [comment]
I've changed the style of the thank you message a bit. The suggested design breaks when in a non-monospace font, the new design tries to mitigate that, but I'm suspecting that it breaks with a different font than the one I'm using.

Might it be better using a different kind of "styling"?

**Comment by matchai** [comment]
@all-contributors Please add @jonstodle for code and tests. 🎉
